#!/bin/sh

. /Applications/mampstack-5.6.31-0/scripts/setenv.sh

exec /Applications/mampstack-5.6.31-0/php/sbin/.php-fpm.bin -y /Applications/mampstack-5.6.31-0/php/etc/php-fpm.conf -p /Applications/mampstack-5.6.31-0/php/var/ -c /Applications/mampstack-5.6.31-0/php/etc/php.ini "$@"
