#!/bin/sh

. /Applications/mampstack-5.6.31-0/scripts/setenv.sh
SASL_PATH="/Applications/mampstack-5.6.31-0/common/lib/sasl2"
                export SASL_PATH
exec /Applications/mampstack-5.6.31-0/common/sbin/.saslauthd.bin -f "/Applications/mampstack-5.6.31-0/common/etc/sasldb2" "$@"
